# Dynamic Programming

Lecture 13

In [3]:
# some setup
from functools import lru_cache
from math import inf

## Memoized longest increasing subsequence

In [2]:
@lru_cache(maxsize=None)
def lis_smaller_memoize(sequence, bound):
    """
    Returns the _length_ of the longest subsequence in `sequence` that is 
    smaller than `bound`
    """
    if len(sequence) == 0:
        return 0
    # sequence[:-1] is the sequence without the last element
    wo_last = lis_smaller_memoize(sequence[:-1], bound)
    # sequence[-1] is the last element
    if sequence[-1] < bound:
        w_last = lis_smaller_memoize(sequence[:-1], sequence[-1]) + 1
        return max(wo_last, w_last)
    return wo_last

In [4]:
lis_smaller_memoize((6, 3, 5, 2, 7, 8, 1, 9), inf)

5

## How does `lru_cache` work?

Note that this uses first-class functions, dynamic binding, and closures; it's OK if you don't fully understand these.

In [27]:
def memoize(func):
    cache = dict()
    hits = 0
    misses = 0
    def memoized_func(*args):
        nonlocal cache, hits, misses
        if args not in cache:
            misses += 1
            cache[args] = func(*args)
        else:
            hits += 1
        return cache[args]
    memoized_func.cache = cache
    def stats():
        print("{} hits, {} misses".format(hits, misses))
    memoized_func.stats = stats
    return memoized_func    

In [28]:
def fib(n):
    if n < 2: 
        return n
    return fib(n-1) + fib(n-2)

In [29]:
fib = memoize(fib)
fib(100)

354224848179261915075

In [30]:
fib.stats()

98 hits, 101 misses


## Complexity of memoized LIS

In [31]:
@memoize
def lis_smaller_memoize(sequence, bound):
    """
    Returns the _length_ of the longest subsequence in `sequence` that is 
    smaller than `bound`
    """
    if len(sequence) == 0:
        return 0
    # sequence[:-1] is the sequence without the last element
    wo_last = lis_smaller_memoize(sequence[:-1], bound)
    # sequence[-1] is the last element
    if sequence[-1] < bound:
        w_last = lis_smaller_memoize(sequence[:-1], sequence[-1]) + 1
        return max(wo_last, w_last)
    return wo_last

In [32]:
lis_smaller_memoize((6, 3, 5, 2, 7, 8, 1, 9), inf)

5

In [33]:
lis_smaller_memoize.stats()

17 hits, 45 misses


What calls _are_ made to `lis_smaller_memoize`?

In [34]:
lis_smaller_memoize.cache

{((), inf): 0,
 ((), 6): 0,
 ((6,), inf): 1,
 ((), 3): 0,
 ((6,), 3): 0,
 ((6, 3), inf): 1,
 ((), 5): 0,
 ((6,), 5): 0,
 ((6, 3), 5): 1,
 ((6, 3, 5), inf): 2,
 ((), 2): 0,
 ((6,), 2): 0,
 ((6, 3), 2): 0,
 ((6, 3, 5), 2): 0,
 ((6, 3, 5, 2), inf): 2,
 ((), 7): 0,
 ((6,), 7): 1,
 ((6, 3), 7): 1,
 ((6, 3, 5), 7): 2,
 ((6, 3, 5, 2), 7): 2,
 ((6, 3, 5, 2, 7), inf): 3,
 ((), 8): 0,
 ((6,), 8): 1,
 ((6, 3), 8): 1,
 ((6, 3, 5), 8): 2,
 ((6, 3, 5, 2), 8): 2,
 ((6, 3, 5, 2, 7), 8): 3,
 ((6, 3, 5, 2, 7, 8), inf): 4,
 ((), 1): 0,
 ((6,), 1): 0,
 ((6, 3), 1): 0,
 ((6, 3, 5), 1): 0,
 ((6, 3, 5, 2), 1): 0,
 ((6, 3, 5, 2, 7), 1): 0,
 ((6, 3, 5, 2, 7, 8), 1): 0,
 ((6, 3, 5, 2, 7, 8, 1), inf): 4,
 ((), 9): 0,
 ((6,), 9): 1,
 ((6, 3), 9): 1,
 ((6, 3, 5), 9): 2,
 ((6, 3, 5, 2), 9): 2,
 ((6, 3, 5, 2, 7), 9): 3,
 ((6, 3, 5, 2, 7, 8), 9): 4,
 ((6, 3, 5, 2, 7, 8, 1), 9): 4,
 ((6, 3, 5, 2, 7, 8, 1, 9), inf): 5}

In [35]:
sorted(set(x[0] for x in lis_smaller_memoize.cache.keys()))

[(),
 (6,),
 (6, 3),
 (6, 3, 5),
 (6, 3, 5, 2),
 (6, 3, 5, 2, 7),
 (6, 3, 5, 2, 7, 8),
 (6, 3, 5, 2, 7, 8, 1),
 (6, 3, 5, 2, 7, 8, 1, 9)]

These are all the prefixes of the sequence

In [36]:
set(x[1] for x in lis_smaller_memoize.cache.keys())

{1, 2, 3, 5, 6, 7, 8, 9, inf}

These are all elements of the sequence, plus the sentinel $\infty$

In [38]:
import sys
!{sys.executable} -m pip install pandas
import pandas as pd

    100% |████████████████████████████████| 14.4MB 1.9MB/s ta 0:00:011
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl


In [54]:
import numpy as np

In [69]:
seq = (6, 3, 5, 2, 7, 8, 1, 9, inf)
data = [ [ str(lis_smaller_memoize.cache.get( (seq[:j], seq[i]), "")) for i in range(9)] for j in range(9)]
df = pd.DataFrame(data, index=[str(seq[:i]) for i in range(9)],
                  columns=["{}".format(seq[i]) for i in range(9)])

In [70]:
df

6  3  5  2  7  8  1  9 inf
()                        0  0  0  0  0  0  0  0   0
(6,)                         0  0  0  1  1  0  1   1
(6, 3)                          1  0  1  1  0  1   1
(6, 3, 5)                          0  2  2  0  2   2
(6, 3, 5, 2)                          2  2  0  2   2
(6, 3, 5, 2, 7)                          3  0  3   3
(6, 3, 5, 2, 7, 8)                          0  4   4
(6, 3, 5, 2, 7, 8, 1)                          4   4
(6, 3, 5, 2, 7, 8, 1, 9)                           5

In [71]:
seq = (6, 3, 5, 2, 7, 8, 1, 9, inf)
data = [ [ str(lis_smaller_memoize.cache.get( (seq[:j], seq[i]), "")) for i in range(9)] for j in range(9)]
df2 = pd.DataFrame(data, index=range(9), columns=range(1,10))

In [75]:
df2

1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0
1     0  0  0  1  1  0  1  1
2        1  0  1  1  0  1  1
3           0  2  2  0  2  2
4              2  2  0  2  2
5                 3  0  3  3
6                    0  4  4
7                       4  4
8                          5

Rename row to $i$ to represent the length-$i$ prefix of the sequence.

Rename column to $j$ to represent the $j$-th element in the sequence (adding $\infty$ at the end)

$A[i,j] = $ `lis_smaller_memoize` ($seq[0:i], seq[j]$)

$A[i,j] = $ `lis_smaller_memoize` ($seq[0:i], seq[j]$)

If seq[i] $\geq$ seq[j], then $A[i,j] = A[i-1,j]$

If seq[i] < seq[j], Then $A[i,j] = \max(A[i-1,j), A[i-1,i]+1)$

$A[0,j] = 0$

If seq[i] $\geq$ seq[j], then $A[i,j] = A[i-1,j]$

If seq[i] < seq[j], Then $A[i,j] = \max(A[i-1,j), A[i-1,i]+1)$

$A[0,j] = 0$

In [103]:
def lis_iterative(sequence):
    # add infinity at the end, 
    # make sequence one-indexed to make things easier
    extended_seq = [None] + sequence + [inf]
    # initialize array to 0's
    A = np.zeros((len(sequence)+1,len(sequence)+2), dtype=np.int8)
    for i in range(1, len(sequence)+1):
        for j in range(i+1, len(sequence)+2):
            if extended_seq[i] < extended_seq[j]:
                A[i][j] = max(A[i-1][j],A[i-1][i]+1)
            else:
                A[i][j] = A[i-1][j]
    print(A)
    return A[len(sequence)][len(sequence)+1]
        

In [105]:
lis_iterative([6, 3, 5, 2, 7, 8, 1, 9])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 1]
 [0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 2 2 0 2 2]
 [0 0 0 0 0 2 2 0 2 2]
 [0 0 0 0 0 0 3 0 3 3]
 [0 0 0 0 0 0 0 0 4 4]
 [0 0 0 0 0 0 0 0 4 4]
 [0 0 0 0 0 0 0 0 0 5]]


5

In [108]:
basic_english_words = set("understandings|understanding|conversations|disappearing|informations|grandmothers|grandfathers|questionings|conversation|information|approaching|understands|immediately|positioning|questioning|grandmother|travellings|questioners|recognizing|recognizers|televisions|remembering|rememberers|expressions|discovering|disappeared|interesting|grandfather|straightest|controllers|controlling|considering|remembered|cigarettes|companying|completely|spreadings|considered|continuing|controlled|stationing|controller|straighter|stretching|businesses|somebodies|soldiering|countering|darknesses|situations|directions|disappears|younglings|suggesting|afternoons|breathings|distancing|screenings|schoolings|especially|everything|everywhere|explaining|explainers|expression|branchings|revealings|repeatings|surprising|rememberer|somewheres|television|themselves|recognizer|recognizes|recognized|belongings|finishings|travelling|questioner|beginnings|travelings|questioned|followings|pretending|forgetting|forgetters|forwarding|positioned|travellers|gatherings|perfecting|understand|understood|weightings|approaches|officering|numberings|happenings|mentioning|letterings|husbanding|imaginings|approached|apartments|whispering|interested|discovered|spinnings|clearings|climbings|spendings|clothings|colorings|soundings|truckings|somewhere|troubling|companies|companied|beautiful|computers|confusing|considers|travelers|youngling|continues|continued|traveller|traveling|yellowing|apartment|beginning|wheelings|travelled|sometimes|something|appearing|cornering|believing|countered|believers|countries|soldiered|coverings|creatures|crossings|accepting|daughters|belonging|situation|silvering|different|silencing|touchings|bettering|tomorrows|disappear|thinkings|boardings|discovers|admitting|wrappings|distances|distanced|sightings|shrugging|doctoring|showering|shoulders|shoppings|shootings|dressings|sheetings|shadowing|settlings|servicing|seriously|seconding|searching|weighting|screening|screaming|schooling|teachings|bothering|everybody|botherers|bottoming|excepting|expecting|explained|direction|explainer|surprised|surprises|waterings|branching|revealing|returning|surfacing|familiars|repeating|fathering|reminding|supposing|breasting|attacking|remembers|breathing|remaining|breathers|brightest|brownings|suggested|recognize|fightings|attention|figurings|receiving|reasoning|realizing|fingering|buildings|finishing|stupidest|stuffings|questions|watchings|flashings|strongest|strikings|flighting|flowering|promisers|promising|following|bathrooms|prettiest|pretended|stretched|foreheads|foresting|stretches|forgotten|pressings|forgetter|strangest|preparing|forwarded|strangers|possibles|positions|afternoon|straights|pocketing|gardening|pleasings|wondering|gathering|picturing|personals|perfected|stomaches|stomached|carefully|stationed|catchings|parenting|paintings|orderings|groupings|wintering|officered|offerings|centering|numbering|neighbors|certainly|happening|narrowing|narrowest|mountains|mothering|mirroring|middlings|messaging|standings|mentioned|mattering|marriages|histories|machining|hospitals|listening|lightings|springing|lettering|husbanded|spreaders|whispered|imagining|imaginers|spreading|important|languages|answering|cigarette|interests|spiriting|cleanings|knockings|soundest|coatings|sounders|sounding|colleges|coloring|colorful|wouldn't|training|colorers|sorriest|worrying|belonged|approach|tracking|touchers|touching|computer|whatever|toppings|confused|confuses|workings|consider|bettered|teething|tonights|tonguers|tonguing|continue|arriving|tomorrow|controls|together|blacking|blackest|throwers|blocking|throwing|coolings|someones|blockers|somebody|thirties|soldiers|cornered|weighted|counting|thoughts|counters|thinking|thinners|thinning|coursing|covering|thinnest|craziest|snapping|creating|creature|thickest|boarding|crossing|smokings|crowding|smelling|smallest|cuttings|slipping|slightly|dancings|sleepers|sleeping|slamming|wordings|darkness|daughter|boatings|skinning|weddings|thanking|sittings|deciding|deciders|singling|singings|despites|simplest|terrible|silvered|tellings|wearings|youngest|watering|silences|teachers|bookings|agreeing|teaching|discover|attacked|bothered|botherer|watching|swingers|bottling|distance|silenced|signings|bottomed|sighting|shutting|shrugged|wondered|swinging|doctored|sweetest|showered|showings|doorways|shouting|shoulder|wronging|shortest|surprise|dragging|shopping|shooters|drawings|actually|shooting|dreaming|dressing|avoiding|shitting|shirting|shipping|drinking|drinkers|braining|sheeting|sharpest|drivings|sharpers|dropping|droppers|shadowed|surfaced|settling|washings|settings|services|serviced|earliest|backings|earthing|servings|branches|branched|seconded|seatings|surfaces|searched|searches|walkings|screened|waitings|screamed|supposed|emptiest|emptying|breaking|breakers|schooled|enjoying|enjoyers|entering|runnings|breasted|rounders|rounding|supposes|everyone|visitors|visiting|breathed|excepted|roofings|exciting|breathes|expected|rollings|bankings|breather|explains|villages|bridging|viewings|brighter|ringings|righting|suitings|bringing|revealed|bringers|returned|failings|repliers|replying|repeated|brothers|familiar|wintered|families|suggests|farthest|furthest|browning|fathered|removing|building|reminded|bathroom|allowing|suddenly|remember|allowers|feedings|builders|burnings|feelings|remained|refusing|stupider|windings|although|stuffing|studying|business|angriest|fighting|fighters|students|figuring|received|twenties|receives|fillings|reasoned|findings|stronger|turnings|realizes|realized|readiest|fingered|readying|striking|trusters|finishes|trusting|finished|readings|reachers|reaching|quieters|quietest|quieting|fittings|quickest|writings|beaching|question|trucking|callings|stranger|flashing|beatings|answered|flattest|flatting|flighted|straight|troubled|flowered|pullings|storming|promiser|couldn't|promised|promises|couldn’t|followed|stoppers|problems|probably|prettier|stopping|pretends|stomachs|troubles|pressers|tripping|forehead|stickers|forested|pressing|whispers|carrying|sticking|carriers|stepping|stealers|forwards|stealing|becoming|prepares|prepared|powering|freeings|stations|possible|position|freshest|beddings|wrapping|fronting|catching|fuckings|policing|funniest|pointers|pointing|catchers|pocketed|gardened|starters|ceilings|pleasing|gathered|starting|centered|platings|plastics|planning|pictured|pictures|traveler|pickings|personal|glancing|yourself|chancing|perfects|changing|peopling|partying|partings|parented|grabbing|grabbers|changers|checking|starring|bedrooms|checkers|pairings|standing|painting|outsides|greatest|cheeking|greening|greenest|grouping|ordering|anything|openings|guarding|wheeling|officers|guessing|spreader|offering|children|anywhere|numbered|choicest|noticers|noticing|hallways|nothings|hangings|nobodies|admitted|neighbor|choosing|choosers|happened|neckings|happiest|narrowed|narrower|spotting|churches|mouthing|traveled|mountain|mothered|accepted|mornings|mirrored|headings|spirited|hearings|heatings|circling|middling|messaged|messages|heaviest|wouldn’t|spinners|mentions|helpings|cleanest|memories|meetings|meanings|appeared|mattered|marrieds|marrying|marriage|yellowed|markings|cleaning|managing|cleaners|holdings|machined|machines|lunching|luckiest|lowering|longings|clearest|hospital|lockings|littlest|clearing|listened|housings|lightest|lighting|lighters|spinning|hundreds|hurrying|believes|spenders|believed|climbing|husbands|lettered|lettings|learning|leadings|ignoring|laughing|ignorers|imagines|yellower|imagined|climbers|imaginer|spending|closings|specials|speakers|language|believer|clothing|clouding|speaking|interest|spacings|landings|knowings|southest|jacketed|knocking|kitchens|kissings|killings|keepings|dresses|biggest|sticker|careful|shirted|warmers|shipped|birding|drinker|carries|sheeted|warming|carried|carrier|driving|sharper|tonight|drivers|casings|sharers|sharing|stepped|dropped|dropper|whisper|shapers|shaping|shakers|shaking|tonguer|shadows|stealer|several|tongued|staying|settles|settled|dusting|setting|tongues|catting|backing|catches|earlier|warmest|earthed|service|serving|warring|wanters|catcher|serious|eastest|sensing|senders|easiest|sending|sellers|selling|seeming|seeings|tiniest|seconds|station|causing|seating|edgings|stating|timings|efforts|starter|causers|screens|blacker|ceiling|screams|centers|wanting|walling|walkers|certain|emptied|empties|emptier|thrower|endings|started|schools|scarers|scaring|sayings|engines|savings|sanding|enjoyed|starers|saddest|enjoyer|staring|enoughs|rushing|bagging|runners|entered|running|chances|entires|chancer|rubbing|rowings|rounder|chanced|rounded|starred|rooming|changed|changes|blocked|angrier|exactly|changer|blocker|excepts|checked|excited|walking|excites|roofing|through|expects|blooded|checker|cheeked|throats|explain|wakings|springs|thought|waiting|blowing|rolling|rocking|risings|ringing|baggers|animals|righter|righted|ridings|richest|facings|reveals|blowers|choicer|choices|returns|voicing|worries|resting|chooses|failing|spreads|replier|failers|falling|spotted|replies|replied|chooser|thinned|fallers|thinner|balling|boarded|repeats|visitor|farther|further|circles|another|removed|fastest|removes|fathers|thicker|circled|visited|reminds|fearing|spirits|classes|answers|banking|boating|cleaned|feeding|spinner|thanked|village|worried|feeling|cleaner|remains|cleared|refuses|refused|workers|reddest|telling|yellows|spender|working|clearer|clearly|climbed|tearing|fighter|teaming|figured|figures|booking|viewing|climber|usually|closest|receive|filling|teacher|reasons|closing|finally|closers|anybody|finding|anymore|realize|special|finders|booting|realest|clothed|readier|readies|readied|fingers|teaches|tallest|clothes|speaker|readers|talkers|clouded|talking|reading|firings|spacing|takings|reacher|reached|coating|reaches|raising|raining|fishing|quietly|fittest|fitting|systems|whether|bothers|wrapped|fitters|quieted|quieter|quickly|coffees|quicker|fixings|coldest|sounded|sounder|actings|anyways|college|flashed|flashes|bottles|flatter|flatted|colored|bottled|wording|turning|sorting|flights|colorer|putting|pushers|pushing|flowers|pullers|swinger|wonders|sorrier|pulling|proving|comings|bottoms|promise|truster|boxings|company|follows|younger|trusted|sweeter|yelling|problem|without|beached|footing|confuse|beaches|brained|bearing|pretend|trucked|forcing|presser|wishing|trouble|forests|appears|beating|airings|forever|surface|control|forgets|accepts|pressed|wronged|winters|forming|presses|prepare|beaters|breaker|wheeled|because|forward|coolers|cooling|allowed|powered|pourers|freeing|pouring|tripped|coolest|breasts|someone|fresher|suppose|somehow|friends|breaths|copping|fronted|becomes|porches|poppers|popping|poorest|treeing|fucking|fullest|pooling|breathe|polices|funnier|funnies|policed|bedding|corners|futures|pointer|pointed|gamings|counted|soldier|pockets|wetting|pleased|gardens|wetters|wettest|pleases|counter|sunning|players|westest|country|gathers|bridges|playing|plating|bridged|plastic|couples|softest|getting|planned|getters|placing|gifting|pinking|pilings|piecing|picture|coursed|courses|summers|picking|snowing|phoning|bedroom|glances|glanced|winging|snapped|glassed|glasses|perhaps|covered|crazies|crazier|perfect|peopled|persons|peoples|suiting|pausing|passing|goldest|partied|windows|parties|parting|creates|grabbed|smokers|created|grabber|brought|weights|bringer|arrives|crosser|crosses|grasses|parents|palming|graying|pairing|crossed|painted|arrived|greying|smoking|paining|outside|brother|greater|smilers|outings|greened|greener|crowded|travels|smiling|ordered|grounds|offings|smelled|openers|browner|grouped|opening|smaller|growing|okaying|officer|guarded|slowest|slowing|cupping|slipped|guessed|guesses|cutting|offices|gunning|offered|browned|allower|nursing|numbing|suggest|cutters|numbers|sliders|halving|sliding|noticer|wedding|notices|noticed|nothing|writers|hallway|handing|sleeper|normals|noising|hanging|nodding|dancing|wearing|writing|slammed|hangers|darkest|skinned|happens|trained|needing|builder|beliefs|happier|necking|nearest|hardest|nearing|burning|believe|winding|hatting|narrows|stupids|sitting|mouthed|deadest|watered|sisters|mothers|singled|winning|morning|mooning|moments|heading|missing|decides|decided|decider|mirrors|minutes|hearing|minings|already|minding|middled|heating|burners|singles|middles|deepest|stuffed|heaters|singing|simpler|heavier|heavies|belongs|message|despite|mention|simples|studies|studied|silvers|helping|helpers|members|meeting|willing|meanest|attacks|herself|meaning|dinners|student|hidings|matters|marries|married|busying|busiest|silence|against|highest|wildest|hilling|marking|mapping|manages|managed|himself|history|tracked|strikes|manning|hitting|makings|hitters|whiting|towards|watched|holding|toucher|machine|holders|lunches|lunched|watches|luckier|stretch|streets|lowered|loudest|lookers|looking|longing|calling|longest|locking|bending|washing|signing|hottest|littler|benders|strange|sighted|listens|linings|likings|housing|beneath|sighing|sicking|however|lighted|sickest|lighter|calming|lifters|hundred|calmest|hurried|hurries|lifting|touched|doesn't|doesn’t|hurting|touches|showers|husband|doctors|letters|cameras|letting|tossing|leaving|learned|dogging|leaning|leafing|leaders|leading|whitest|layered|ignored|showing|ignores|stories|ignorer|shoving|laughed|lasting|largest|imaging|doorway|besting|imagine|shouted|stormed|downing|storing|topping|avoided|dragged|shorter|betters|stopper|landers|insides|instead|written|drawing|shopped|stopped|between|landing|shooter|knowing|jackets|dreamed|carding|toothed|knocked|knifing|kitchen|joining|teethed|stomach|joiners|kissing|kindest|killers|killing|shoeing|kidding|jumping|kickers|kicking|jumpers|keepers|dressed|keeping|enough|checks|kicked|jumper|kicker|kidded|jumped|killed|joking|killer|kinder|joiner|kisses|kissed|joined|knives|knifes|knifed|jacket|knocks|itself|ladies|landed|lander|inside|larger|images|lasted|imaged|laughs|ignore|aboves|laying|accept|layers|across|yellow|leaded|leader|leaved|leaned|learns|leaves|yelled|lesser|letter|living|lifted|lifter|humans|hugest|lights|wrongs|houses|liking|likers|lining|housed|acting|listen|hotels|little|hotter|locals|locked|horses|longer|longed|looked|hoping|looker|losing|adding|louder|loving|lovers|lowing|lowest|writer|lowers|homing|holing|holder|making|hitter|makers|manned|manage|writes|admits|mapped|marked|hilled|higher|afraid|hiding|hidden|matter|ageing|helper|member|helped|memory|hellos|heater|metals|middle|heated|mights|minded|hearts|mining|minute|headed|mirror|misses|missed|moment|moneys|monies|months|mooned|mostly|having|mother|worlds|hating|mouths|moving|movers|movies|musics|worker|myself|naming|namers|narrow|hatted|hardly|nearer|neared|nearly|harder|necked|needed|happen|hanger|newest|nicest|nights|worked|nobody|nodded|handed|noises|noised|worded|normal|norths|nosing|agrees|noting|notice|halves|halved|number|guying|numbed|nurses|nursed|agreed|wooden|offing|gunned|offers|office|guards|wonder|okayed|okay'd|okay’d|ok'ing|ok’ing|oldest|womens|opened|opener|groups|womans|within|ground|orders|others|outing|wished|greens|greats|owning|wishes|owners|paging|pained|paints|greyed|greyer|paired|palest|grayed|palmed|papers|grayer|parent|parted|passed|golder|passes|pauses|paused|paying|person|people|wipers|goings|glance|phones|phoned|photos|picked|giving|givens|pieces|pieced|piling|gifted|pinked|pinker|places|placed|getter|gotten|plated|plates|gently|played|gather|player|please|gating|garden|pocket|gamers|points|pointy|gaming|future|wiping|fuller|police|pooled|poorer|fucked|popped|popper|fronts|friend|freers|poured|pourer|freest|powers|formed|forget|forgot|forest|forces|forced|footed|pretty|follow|fliers|flyers|proven|airing|proves|proved|prover|pulled|flying|puller|flower|pushes|pushed|floors|pusher|flight|fixers|fixing|quicks|winter|fitted|quiets|fitter|winged|radios|rained|raises|raised|fishes|rather|fished|firsts|firing|reader|finish|finger|fining|finest|realer|finder|really|finals|reason|filled|figure|fought|fights|fields|fewest|redder|refuse|remain|feeing|remind|feared|father|faster|remove|repeat|family|faller|fallen|failer|failed|rested|fading|return|reveal|riches|richer|riding|ridden|window|riders|rights|facing|allows|ringed|rising|rivers|extras|rocked|rolled|expect|roofed|excite|except|rooves|roomed|events|rounds|rowing|evened|rubbed|almost|entire|runner|enters|keying|rushed|rushes|sadder|safest|sanded|enjoys|saving|engine|savers|winded|saying|enders|scared|scares|scarer|scenes|ending|school|scream|either|eights|screen|egging|effort|search|edging|seated|second|eaters|seeing|seemed|eating|seller|sender|senses|sensed|easier|easily|earths|serves|served|willed|dusted|settle|during|driers|sevens|sexing|shadow|shakes|shaken|dryers|shaker|always|shaped|driest|shapes|shaper|drying|shares|shared|sharer|sharps|driver|drives|driven|sheets|droves|drinks|shirts|drunks|shoots|dreams|shorts|dozens|should|downed|shouts|shoved|shoves|showed|wilder|shower|dogged|doctor|shrugs|didn’t|sicker|sicked|didn't|siding|sighed|doings|sights|signed|dinner|silent|silver|dyings|widest|simple|simply|deeper|single|decide|deaths|sister|deader|sizing|darker|wholes|sleeps|dances|danced|slides|slider|cutter|slower|slowed|slowly|smalls|cupped|smells|smelly|crying|smiles|smiled|smiler|crowds|smokes|smoked|smoker|create|covers|snowed|whited|softer|course|softly|couple|counts|corner|whiter|copped|cooled|cooler|coming|whites|sorted|colors|colder|sounds|coffee|coated|spaces|clouds|spaced|spoken|speaks|clothe|closed|closes|closer|spends|climbs|clears|cleans|spirit|cities|circle|church|choose|spread|chosen|choice|chests|sprung|spring|sprang|stages|stairs|cheeks|stands|keeper|change|chance|stared|stares|starer|chairs|starts|center|causer|caused|states|stated|causes|caught|catted|stayed|steals|stolen|casing|sticks|caring|carded|stones|animal|cannot|stored|stores|storms|answer|camera|calmer|calmed|called|street|buyers|bought|strike|struck|buying|anyone|strong|busier|busied|busing|burner|stuffs|burned|stupid|builds|browns|suites|suited|brings|summer|bright|sunned|bridge|breath|breast|breaks|broken|surest|branch|brains|anyway|boxing|wheels|sweets|swings|bottom|bottle|system|bother|tables|taking|takers|talked|talker|boring|taller|booted|taught|booked|teamed|teared|boning|appear|bodies|thanks|boated|thicks|boards|bluest|things|thinks|blower|thirds|thirty|though|threes|throat|bloods|thrown|throws|blocks|timing|blacks|timers|tinier|biters|tiring|todays|biting|toning|tongue|arming|birded|bigger|wetter|toothy|beyond|better|topped|tossed|bested|tosses|beside|bender|toward|bended|tracks|belong|trains|belief|travel|behind|begins|before|bedded|became|become|beater|beaten|trucks|truest|aren’t|aren't|trusts|truths|trying|turned|twenty|around|uncles|weight|wasn’t|wasn't|arrive|unless|upping|wedded|viewed|barely|visits|banked|balled|voices|voiced|waited|bagger|waking|walked|bagged|walker|walled|asking|wanted|wanter|warred|waring|backed|warmed|warmer|babies|washed|washes|avoids|attack|waters|asleep|watery|waving|wavers|seems|party|minds|eaten|sells|sends|known|sense|hours|pasts|paths|easts|pause|mined|layer|payed|serve|earth|early|wills|aired|heard|hears|dusts|kills|goers|hotel|seven|dried|ideas|sexed|sexes|going|drier|dries|dryer|glass|heads|shake|leads|shook|aging|gives|phone|local|photo|shape|picks|above|locks|money|drops|share|given|wrong|girls|month|sharp|piece|wilds|sheet|drove|drive|moons|lands|piles|ships|drink|piled|drank|drunk|shirt|pinks|shits|dress|shoes|mores|shoot|longs|shots|dream|drawn|draws|drags|shops|haves|horse|short|gifts|dozen|place|downs|shout|hopes|shove|hoped|plans|wiper|doors|shown|shows|wiped|plate|world|mouth|doers|joins|shrug|shuts|leafs|moved|plays|moves|sicks|don’t|pleas|sided|sides|sighs|don't|gated|sight|looks|gates|wives|mover|signs|doing|dirts|knees|movie|learn|gamer|games|gamed|dying|music|since|desks|sings|singe|deeps|point|acted|musts|yells|funny|death|wider|loses|sixes|whose|names|sizes|sized|skins|keyed|skies|pools|slams|darks|named|slept|namer|sleep|leave|dance|slide|hated|young|whole|fucks|who’s|slips|who's|slows|front|porch|loved|hates|small|fresh|cries|cried|smell|white|nears|loves|smile|freer|pours|lover|freed|power|smoke|frees|yeses|crowd|cross|jokes|fours|snaps|crazy|forms|cover|homed|snows|among|necks|happy|least|press|force|homes|count|needs|wipes|years|cools|foots|joked|foods|never|songs|comes|sorry|flier|color|sorts|souls|lower|newer|flyer|colds|sound|flown|south|works|coats|space|nicer|prove|lucky|spoke|night|speak|cloud|hurts|yards|pulls|holed|flies|close|climb|spent|spend|words|holes|hangs|clear|lunch|spins|clean|class|liars|floor|holds|spots|alive|noise|flats|chose|flash|nones|child|fixer|fixed|fixes|chest|cheek|mains|stage|hands|makes|stair|quick|stood|check|fiver|stand|stars|fives|north|wrote|stare|lying|quiet|noses|quite|start|chair|nosed|radio|lived|rains|notes|state|large|cause|raise|catch|noted|maker|stays|halls|angry|stole|steal|reach|first|cased|cases|steps|lives|fires|stuck|carry|stick|cares|still|cared|fired|cards|added|stone|reads|halve|stops|write|can’t|ready|hairy|store|hairs|can't|storm|numbs|story|could|finer|knife|fines|calms|fined|calls|hurry|while|buyer|finds|nurse|found|which|lifts|admit|final|fills|lasts|keeps|where|buses|bused|study|offed|stuff|fight|woods|burnt|burns|field|human|build|built|wings|offer|brown|allow|guyed|suite|suits|bring|marks|fewer|feels|hills|wines|later|feeds|agree|guess|surer|fears|broke|break|guard|brain|highs|often|marry|ahead|knock|boxes|sweet|boxed|okays|swing|swung|falls|reply|hides|fails|huger|table|takes|taken|laugh|taker|rests|house|talks|bored|women|faded|fades|wheel|facts|wraps|boots|teach|faces|teams|older|books|tears|bones|maybe|woman|faced|areas|boned|opens|tells|rides|grows|thank|their|boats|thens|there|these|thick|rider|after|board|right|bluer|thins|blues|blued|grown|thing|again|rings|think|blows|blown|third|would|means|those|risen|three|rises|blood|eying|heres|throw|block|threw|roses|group|river|black|tying|times|timed|roads|rocks|order|timer|meant|green|tired|tires|extra|meets|today|rolls|biter|bitey|other|toned|tones|light|bites|worry|birds|roofs|armed|outer|rooms|outed|every|tooth|teeth|round|image|bests|event|liked|evens|rowed|likes|touch|bends|windy|bents|towns|winds|great|below|track|overs|owned|liker|train|enter|wound|begun|helps|began|begin|owner|beers|kinds|wests|paged|trees|treed|tripe|trips|pages|alone|hello|beats|enjoy|bears|truck|beach|safer|trues|truer|trued|safes|hells|sames|trust|truth|pains|wells|sands|tried|tries|greys|turns|isn’t|isn't|heavy|twice|saves|uncle|saved|under|kicks|saver|paint|lines|grays|until|weeks|upped|pairs|using|asked|usual|scare|being|ender|metal|views|paled|banks|visit|pales|paler|voice|scene|heats|waits|balls|ended|empty|woken|palms|wakes|waked|walks|lined|knows|pants|worse|paper|walls|worst|wants|eight|heart|along|backs|egged|jumps|warms|grass|might|edges|grabs|seats|avoid|parts|edged|aunts|watch|about|eater|won’t|water|won't|waved|waves|goods|waver|golds|wears|ears|grab|fits|each|sets|knee|lots|part|dust|noes|fish|stay|good|rain|cats|work|wild|laid|hang|gold|pass|step|loud|case|help|your|past|nods|home|care|path|hell|read|love|fire|gods|lift|card|stop|pays|keys|cars|paid|idea|fine|none|real|into|drop|heat|wish|cans|kids|find|goer|goes|went|calm|just|lead|gone|call|fill|nose|ship|huge|acts|lows|buys|some|note|kind|shit|shat|mind|ices|busy|pick|hand|shod|shoe|gave|reds|shot|hall|fews|ours|feel|burn|drew|such|draw|shop|give|felt|wing|suit|drag|hear|feed|mine|girl|feds|iced|down|when|fees|half|suns|able|word|fear|nows|door|fast|sure|leaf|pile|jobs|show|wine|boys|dogs|yell|hair|guys|kept|doer|fall|fell|head|shut|gift|hole|rest|numb|kick|lean|take|both|sick|fail|fade|took|miss|side|sigh|held|talk|last|plan|bore|hold|done|tall|teas|fact|boot|like|wife|rich|sign|book|wood|team|does|main|offs|tear|tore|torn|rode|dirt|gets|bone|joke|ride|make|told|play|died|tell|dies|tens|area|body|than|boat|line|guns|desk|that|what|kiss|them|they|gate|sang|then|plea|kill|face|sing|sung|eyes|thin|blue|deep|made|rung|ring|sirs|wide|he’s|rang|moon|blow|eyed|sits|more|whys|dead|blew|days|this|left|grew|he's|size|rise|rose|whom|have|skin|most|late|grow|slam|road|game|tied|ties|arms|time|dark|rock|okay|ages|mens|roll|mans|tiny|slid|dads|airs|ok'd|tire|wets|ok’d|i’ll|roof|slip|full|cuts|pool|slow|tone|bite|lips|cups|bits|room|olds|poor|bird|adds|ever|knew|hate|fuck|pops|even|tops|wipe|hits|once|west|hour|rows|rubs|toss|best|ones|only|from|runs|bend|bent|onto|open|move|town|free|pour|legs|rush|jump|snap|many|hill|less|maps|snow|keep|safe|much|soft|join|beer|i'll|beds|four|tree|same|sand|form|cops|must|year|cool|trip|lets|beat|mark|born|bear|with|come|save|know|true|sons|lock|song|soon|laws|came|outs|name|well|been|says|said|sort|feet|soul|high|yeah|were|hide|foot|turn|cold|wind|yard|twos|coat|food|over|hats|owns|ends|lady|aged|arts|else|long|flew|hurt|page|week|upon|lays|used|uses|hard|eggs|wins|very|mays|seas|pain|near|view|bars|weds|pull|edge|wrap|lies|bank|spin|ball|grey|seat|spun|lied|neck|push|wait|hope|bags|city|look|wake|spot|saws|woke|wear|pink|liar|eats|walk|need|sees|seen|puts|seem|wall|want|pair|gray|sell|will|flat|back|pale|sold|asks|wars|land|send|mean|warm|baby|sent|also|wash|away|here|easy|hung|sens|star|hers|aunt|palm|worn|life|meet|wore|east|live|news|five|wave|next|lost|lose|nice|ways|far|few|war|bad|bag|bar|wed|use|ups|art|was|two|try|are|bed|top|arm|wet|big|too|bit|tie|the|ten|tvs|tea|box|boy|sun|bus|but|buy|any|can|car|cat|and|son|cop|sos|cry|cup|cut|who|dad|sky|day|six|why|sit|sat|sir|die|did|dog|she|dry|sex|set|ear|ate|eat|see|saw|win|won|sea|egg|end|say|sad|ran|run|rub|row|eye|rid|ask|fed|fee|red|way|fit|fix|all|put|fly|for|pop|fun|get|got|god|pay|own|out|our|air|ors|one|old|ohs|gun|key|off|guy|now|not|nor|nod|nos|ago|new|hat|age|had|has|her|met|hey|may|hid|map|him|add|his|man|men|hit|mad|low|lot|hot|lip|how|lit|lie|kid|i'm|let|i’m|leg|i'd|i’d|ice|led|act|lay|law|ins|yes|yet|you|its|job|no|at|by|my|on|ha|do|ok|he|oh|is|tv|me|us|as|hi|go|if|of|am|up|to|we|so|in|or|it|be|an|i|a".split('|'));

def StrInL(s):
    return s in basic_english_words

![](https://imgs.xkcd.com/comics/up_goer_five.png)

Image from https://xkcd.com/1133/

## Language containment

Suppose for an arbitrary language $L$, we are given a function `StrInL` to determine whether something is in the language.

In [111]:
StrInL("language")

True

In [112]:
StrInL("arbitrary")

False

In [113]:
StrInL("something")

True

## Sentence

Suppose we are given a sentence and we want to check whether each word is in L.
- "An algorithm for an arbitrary language": False
- "You will not go to space today": True

_But_ someone ate all the spaces so our input is:
- "analgorithmforanarbitrarylanguage"
- "youwillnotgotospacetoday"

What problem is this?

#### Is the string in $L^*$

### Solving the $L^*$ problem

We want an algorithm to determine if a string $w$ is in $L^*$, using `StrInL` as a _black box_

### Recursive solution

Follows straight from the definition of $L^*$.

$w \in L^*$ if $w = uv$ with $u \in L$ and $v \in L^*$

Or $w = \epsilon$

In [176]:
@memoize
def RecStrInLStar(s):
    if len(s) == 0:
        return True
    for i in range(1,len(s)+1):
        # let u = first i characters, v = rest
        u, v = s[i:], s[:i]
        if RecStrInLStar(v):
            if StrInL(u):
                return True
    return False

Note: normally I would write:

```
if StrInL(u) and RecStrInLStar(v):
    return True
```

to limit recursive calls. But I used the slightly less efficient formulation in order to make the linear worst-case runtime easier to see.

In [182]:
RecStrInLStar("youwillnotgotospacetoday")

True

In [183]:
RecStrInLStar.stats()

195 hits, 25 misses


In [184]:
RecStrInLStar("amanaplanacat")

True

### Runtime of `StrInLStar`

We need to answer two questions:
1. How many _distinct_ recursive subproblems are generated by `StrInLStar`, at all levels
2. How much work is done in each subproblem.


1. Each subproblem is a suffix of the string, so $O(n)$ subproblems.

In [185]:
@memoize
def RecStrInLStar(s):
    if len(s) == 0:
        return True
    for i in range(1,len(s)+1):
        # let u = first i characters, v = rest
        if StrInL(s[0:i]) and RecStrInLStar(s[i:]):
            return True
    return False

How much work in each subproblem?

$O(n)$ calls to `StrInL`

Therefore $O(n^2)$ work in total.

### Making memoization explicit

Name each subproblem: $A[i]$ = `StrInLStar`($s[i:]$), for $i = 0, \ldots, n$

$A[n] = $True

$A[i] = $ True if for any $j$ s.t. $i < j \leq n$, $A[i:j] \in L$ and $A[j]$ is True

In [155]:
def IterStrInLStar(s):
    A = [False for _ in range(len(s)+1)]
    A[len(s)] = True
    for i in reversed(range(0,len(s))): # n-1 down to 0
        for j in range(i+1,len(s)+1): # i+1 to n
            if A[j] and StrInL(s[i:j]):
                A[i] = True
                break
    print(A)
    return A[0]

In [156]:
IterStrInLStar("amanaplanacat")

[True, True, True, False, True, True, False, True, False, True, True, True, False, True]


True

In [157]:
IterStrInLStar("youwillnotgotospacetoday")

[True, False, False, True, False, False, False, True, False, False, True, False, True, False, True, False, False, False, False, True, False, True, False, False, True]


True

### Why iterative approach?

Slightly faster, can be further optimized.

Easier to see runtime (though harder to see correctness)

### Reconstruct sentence

Another example: find the shortest sentence in $L^*$ for the string. Similar approach,
but keep track of best "sentenefication" over all possible choice of $w = uv$.

In [186]:
@memoize
def sentenify(s):
    if len(s) == 0:
        return []
    best = None
    for i in range(1,len(s)+1):
        u, v = s[0:i], s[i:]
        if StrInL(u):
            rest = sentenify(v)
            if rest is not None:
                if best is None or len(best) >= len(rest):
                    best = [u] + rest
    return best

In [187]:
sentenify("amanaplanacat")

['am', 'an', 'a', 'plan', 'a', 'cat']

In [188]:
sentenify.stats()

1 hits, 9 misses


### "Dumb" Recursion

Dynamic Programing is smart recursion + memoization

Let's see an example of "dumb" recursion. Instead of splitting a string $w = uv$ with $u \in L$ and $v \in L^*$, we will split it into $w = uvx$, with $u \in L$, $x \in L$, and $v \in L^*$. (We also have to special-case $w \in L$ here.)

This is a bit of a contrived approach but shows that memoization itself isn't enough for efficiency

In [189]:
@memoize
def dumb_in_lstar(s):
    if len(s) == 0:
        return True
    # have to special case 
    if StrInL(s):
        return True
    # break word into start, middle, end
    for i in range(1, len(s)):
        for j in reversed(range(i,len(s))):
            start, middle, end = s[0:i], s[i:j], s[j:]
            if dumb_in_lstar(middle):
                if StrInL(start) and StrInL(end):
                    return True
    return False
    

In [190]:
dumb_in_lstar("amanaplanacataday")

True

In [191]:
dumb_in_lstar.stats()

1208 hits, 87 misses


Note that this results in a quadratic number of subproblems, since potentially every substring of $w$ is used as a recursive subproblem.